add_newline = true

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[✗](bold red)"

[cmd_duration]
disabled = true

[directory]
truncation_length = 0
style = "bold cyan"
read_only = " 󰌾"

[git_branch]
symbol = " "
style = "bold purple"

[package]
disabled = true # Don't show package version (cleaner)

[username]
show_always = true

